server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    username: root
    password: 123456
    url: "jdbc:mysql://localhost:3306/identity_service"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  valid-duration: 5 #in seconds
  refreshable-duration: 120 #in seconds